/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author USER
 */
public class AppointmentWindow extends javax.swing.JFrame {

    /**
     * Creates new form Citas
     */
    public AppointmentWindow() {
        initComponents();
        NumDia.setToolTipText("15");
        this.setLocationRelativeTo(null);
    }
    
    public void setBackBtListener (ActionListener al) {
        this.atrasBt.addActionListener(al);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCitas = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        CampoCedula = new javax.swing.JTextField();
        atrasBt = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        NombreCompleto = new javax.swing.JLabel();
        CampoNombreCompleto = new javax.swing.JTextField();
        Doctor = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Día = new javax.swing.JLabel();
        NumDia = new javax.swing.JSpinner();
        Mes = new javax.swing.JLabel();
        NumMes = new javax.swing.JSpinner();
        Anio = new javax.swing.JLabel();
        NumAnio = new javax.swing.JSpinner();
        Hora = new javax.swing.JLabel();
        NumHora = new javax.swing.JSpinner();
        BotonGuardarCita = new javax.swing.JButton();
        BotonCancelarCita = new javax.swing.JButton();
        Servicio = new javax.swing.JLabel();
        DoctoresDisponibles = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        ServiciosAnadidos = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        BuscadorServicio = new javax.swing.JButton();
        EliminarServicio = new javax.swing.JButton();
        AnadirServicio = new javax.swing.JButton();
        ListaServicios = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        Cedula1 = new javax.swing.JLabel();
        CampoCedula1 = new javax.swing.JTextField();
        BotonBuscar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombreCD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloCitas.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        TituloCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tooth-6783172_1280.png"))); // NOI18N
        TituloCitas.setText("ADMINISTRADOR DE CITAS");
        getContentPane().add(TituloCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 570, -1));

        Cedula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Cedula.setText("CÉDULA");
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 60, 20));

        CampoCedula.setBorder(null);
        getContentPane().add(CampoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 330, 30));

        atrasBt.setText("ATRAS");
        getContentPane().add(atrasBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        BotonBuscar.setBackground(new java.awt.Color(0, 80, 130));
        BotonBuscar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscar.setText("BUSCAR");
        BotonBuscar.setBorder(null);
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 80, 30));

        NombreCompleto.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        NombreCompleto.setText("NOMBRE DEL PACIENTE");
        getContentPane().add(NombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 220, 20));

        CampoNombreCompleto.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        CampoNombreCompleto.setBorder(null);
        getContentPane().add(CampoNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 330, 30));

        Doctor.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Doctor.setText("DOCTOR");
        Doctor.setToolTipText("");
        getContentPane().add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, 20));

        Fecha.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Fecha.setText("FECHA");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        Día.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Día.setText("Día");
        getContentPane().add(Día, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        getContentPane().add(NumDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        Mes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Mes.setText("Mes");
        getContentPane().add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        getContentPane().add(NumMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        Anio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Anio.setText("Año");
        getContentPane().add(Anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));
        getContentPane().add(NumAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        Hora.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Hora.setText("Hora");
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));
        getContentPane().add(NumHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        BotonGuardarCita.setBackground(new java.awt.Color(0, 80, 130));
        BotonGuardarCita.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonGuardarCita.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardarCita.setText("GUARDAR CITA");
        BotonGuardarCita.setBorder(null);
        getContentPane().add(BotonGuardarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 720, 120, 30));

        BotonCancelarCita.setBackground(new java.awt.Color(0, 80, 130));
        BotonCancelarCita.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonCancelarCita.setForeground(new java.awt.Color(255, 255, 255));
        BotonCancelarCita.setText("CANCELAR CITA");
        BotonCancelarCita.setBorder(null);
        getContentPane().add(BotonCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 720, 140, 30));

        Servicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Servicio.setText("SERVICIO");
        getContentPane().add(Servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 70, 20));

        jList1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        DoctoresDisponibles.setViewportView(jList1);

        getContentPane().add(DoctoresDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, -1));

        jList2.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ServiciosAnadidos.setViewportView(jList2);

        getContentPane().add(ServiciosAnadidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, 250, 180));

        jTextField1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, 30));

        BuscadorServicio.setBackground(new java.awt.Color(0, 80, 130));
        BuscadorServicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BuscadorServicio.setForeground(new java.awt.Color(255, 255, 255));
        BuscadorServicio.setText("BUSCAR");
        BuscadorServicio.setBorder(null);
        getContentPane().add(BuscadorServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 80, 30));

        EliminarServicio.setBackground(new java.awt.Color(0, 80, 130));
        EliminarServicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        EliminarServicio.setForeground(new java.awt.Color(255, 255, 255));
        EliminarServicio.setText("ELIMINAR");
        EliminarServicio.setBorder(null);
        EliminarServicio.setBorderPainted(false);
        getContentPane().add(EliminarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 80, 40));

        AnadirServicio.setBackground(new java.awt.Color(0, 80, 130));
        AnadirServicio.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        AnadirServicio.setForeground(new java.awt.Color(255, 255, 255));
        AnadirServicio.setText("AÑADIR");
        AnadirServicio.setBorder(null);
        getContentPane().add(AnadirServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 90, 40));

        jList3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaServicios.setViewportView(jList3);

        getContentPane().add(ListaServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 250, 180));

        Cedula1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Cedula1.setText("CÉDULA");
        getContentPane().add(Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 20));

        CampoCedula1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        CampoCedula1.setBorder(null);
        getContentPane().add(CampoCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 330, 30));

        BotonBuscar1.setBackground(new java.awt.Color(0, 80, 130));
        BotonBuscar1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        BotonBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscar1.setText("BUSCAR");
        BotonBuscar1.setBorder(null);
        getContentPane().add(BotonBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 80, 30));

        jList4.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList4);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 330, 190));

        jButton1.setBackground(new java.awt.Color(0, 80, 130));
        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EVENTOS");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 90, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("BUSCADOR DE CITAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setText("CREACIÓN DE CITAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 80, 130));
        jButton3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("GENERAR FACTURA");
        jButton3.setBorder(null);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, 170, 40));

        jButton4.setBackground(new java.awt.Color(0, 80, 130));
        jButton4.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MODIFICAR");
        jButton4.setBorder(null);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 90, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel3.setText("DETALLE DE CITAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/074b366d64dcd96e90d1e68482fcc62f.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 560, 560));

        NombreCD.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        NombreCD.setText("ODONTOSALUD");
        getContentPane().add(NombreCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 330, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SeekPng.com_tooth-logo-png_3299701_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Fondo);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1230, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AppointmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AppointmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AppointmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AppointmentWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AppointmentWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirServicio;
    private javax.swing.JLabel Anio;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonBuscar1;
    private javax.swing.JButton BotonCancelarCita;
    private javax.swing.JButton BotonGuardarCita;
    private javax.swing.JButton BuscadorServicio;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoCedula1;
    private javax.swing.JTextField CampoNombreCompleto;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Cedula1;
    private javax.swing.JLabel Doctor;
    private javax.swing.JScrollPane DoctoresDisponibles;
    private javax.swing.JLabel Día;
    private javax.swing.JButton EliminarServicio;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Hora;
    private javax.swing.JScrollPane ListaServicios;
    private javax.swing.JLabel Mes;
    private javax.swing.JLabel NombreCD;
    private javax.swing.JLabel NombreCompleto;
    private javax.swing.JSpinner NumAnio;
    private javax.swing.JSpinner NumDia;
    private javax.swing.JSpinner NumHora;
    private javax.swing.JSpinner NumMes;
    private javax.swing.JLabel Servicio;
    private javax.swing.JScrollPane ServiciosAnadidos;
    private javax.swing.JLabel TituloCitas;
    private javax.swing.JButton atrasBt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
