/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author USER
 */
public class CustomerWindow extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public CustomerWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cedula = new javax.swing.JLabel();
        CampoCedula = new javax.swing.JTextField();
        Nombres = new javax.swing.JLabel();
        CampoNombres = new javax.swing.JTextField();
        Apellidos = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        CampoDireccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        CampoCorreo = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NombreCD = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        TituloClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cedula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Cedula.setText("CÉDULA");
        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 20));

        CampoCedula.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoCedula.setBorder(null);
        getContentPane().add(CampoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 30));

        Nombres.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Nombres.setText("NOMBRES");
        getContentPane().add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        CampoNombres.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoNombres.setBorder(null);
        getContentPane().add(CampoNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        Apellidos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Apellidos.setText("APELLIDOS");
        getContentPane().add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 20));

        CampoApellidos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoApellidos.setBorder(null);
        getContentPane().add(CampoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        Direccion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Direccion.setText("DIRECCIÓN");
        Direccion.setToolTipText("");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 20));

        CampoDireccion.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoDireccion.setBorder(null);
        getContentPane().add(CampoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, 30));

        Telefono.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Telefono.setText("TELÉFONO");
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        CampoTelefono.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoTelefono.setBorder(null);
        getContentPane().add(CampoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 330, 30));

        Correo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        Correo.setText("CORREO ELECTRÓNICO");
        getContentPane().add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, 20));

        CampoCorreo.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        CampoCorreo.setBorder(null);
        getContentPane().add(CampoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 30));

        BotonGuardar.setBackground(new java.awt.Color(0, 80, 130));
        BotonGuardar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setText("GUARDAR");
        BotonGuardar.setBorder(null);
        getContentPane().add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, 30));

        BotonModificar.setBackground(new java.awt.Color(0, 80, 130));
        BotonModificar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonModificar.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificar.setText("MODIFICAR");
        BotonModificar.setBorder(null);
        getContentPane().add(BotonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 30));

        BotonBuscar.setBackground(new java.awt.Color(0, 80, 130));
        BotonBuscar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        BotonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscar.setText("BUSCAR");
        BotonBuscar.setBorder(null);
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SeekPng.com_tooth-logo-png_3299701_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        NombreCD.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        NombreCD.setText("ODONTOSALUD");
        getContentPane().add(NombreCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/teeth-implant-index.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -90, 340, 610));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 330, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 330, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 330, 10));

        TituloClientes.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        TituloClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tooth-6783172_1280.png"))); // NOI18N
        TituloClientes.setText("CLIENTES");
        getContentPane().add(TituloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CustomerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustomerWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoNombres;
    private javax.swing.JTextField CampoTelefono;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreCD;
    private javax.swing.JLabel Nombres;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel TituloClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
