/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author USER
 */
public class MenuWindow extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreMenu = new javax.swing.JLabel();
        BotonClientes = new javax.swing.JButton();
        BotonCitas = new javax.swing.JButton();
        BotonFacturacion = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreMenu.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        NombreMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tooth-6783172_1280.png"))); // NOI18N
        NombreMenu.setText("MENÚ PRINCIPAL");
        getContentPane().add(NombreMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        BotonClientes.setBackground(new java.awt.Color(0, 80, 130));
        BotonClientes.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        BotonClientes.setForeground(new java.awt.Color(255, 255, 255));
        BotonClientes.setText("CLIENTES");
        BotonClientes.setBorder(null);
        BotonClientes.setPreferredSize(new java.awt.Dimension(38, 20));
        getContentPane().add(BotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, 30));

        BotonCitas.setBackground(new java.awt.Color(0, 80, 130));
        BotonCitas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonCitas.setForeground(new java.awt.Color(255, 255, 255));
        BotonCitas.setText("CITAS");
        BotonCitas.setBorder(null);
        getContentPane().add(BotonCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 30));

        BotonFacturacion.setBackground(new java.awt.Color(0, 80, 130));
        BotonFacturacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        BotonFacturacion.setText("FACTURACIÓN");
        BotonFacturacion.setBorder(null);
        getContentPane().add(BotonFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 30));

        BotonSalir.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(0, 80, 130));
        BotonSalir.setText("SALIR");
        BotonSalir.setBorder(null);
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dientes3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 270, 490));

        jButton1.setBackground(new java.awt.Color(0, 80, 130));
        jButton1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 442, 160, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCitas;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonFacturacion;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
